spring.application.name=Review-Service
spring.datasource.url=jdbc:mariadb://review-db:3306/reviewDb?createDatabaseIfNotExist=true
spring.datasource.username=user
spring.datasource.password=123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8082

booking.service.url=http://booking-service:8080
customer.service.url=http://customer-service:8081
