spring.application.name=Review-Service
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:3306/reviewDb?createDatabaseIfNotExist=true
spring.datasource.username=user
spring.datasource.password=123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8082

booking.service.url=http://${BOOKING_SERVICE_HOST:localhost}:8080
customer.service.url=http://${CUSTOMER_SERVICE_HOST:localhost}:8081
